name: Android CI

on:
  push:
#     branches:
#       - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    # 获取打包秘钥
    - name: Checkout Android Keystore
      uses: actions/checkout@v2
      with:
        repository: open-wkg/Keystore
        token: ${{ secrets.TOKEN }}
        submodules: 'true'
        path: keystore
        
       # 获取apk版本号
    - name: Get Version Name
      uses: actions/github-script@v3
      id: get-version
      with:
        script: |
          const str=process.env.GITHUB_REF;
          var index = str.indexOf("v");
          if(index == -1){
            const sha =process.env.GITHUB_SHA;
            return sha.substring(0,7) ;
          }else{
            return str.substring(str.indexOf("v"));
          }
        result-encoding: string
    - name: test2
      run: echo version:${{  steps.get-version.outputs.result }}
    #打包
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    # 创建release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{  steps.get-version.outputs.result }}
        draft: false
        prerelease: false
 
    # 上传至release的资源
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: BikeNfc-${{  steps.get-version.outputs.result  }}.apk
        asset_content_type: application/vnd.android.package-archiv
    # 存档打包的文件
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: app/build/outputs #将打包之后的文件全部上传（里面会有混淆的map文件）
